name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]  
jobs:
  build:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mebyz/ambient-0.1.1-build-action@v1
