name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]  
jobs:
  config:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    runs-on: ubuntu-latest
    steps:
      - uses: engineerd/configurator@v0.0.1
        with:
          name: "ambient"
          url: "https://github.com/AmbientRun/Ambient/releases/download/v0.1.1/ambient-x86_64-unknown-linux-gnu.zip"
          pathInArchive: "ambient"
      - name: config
        run: |
          ambient --help
  build:
    needs: config
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: buiild
      run: ambient build --verbose
